# Architecture 84.1%
arch: CoAtNet2

# ===== Dataset ===== #
data_url: ../data/imagenet
set: ImageNet
num_classes: 1000
mix_up: 0.8
cutmix: 1.0
auto_augment: rand-m9-mstd0.5-inc1
interpolation: random
re_prob: 0.25
re_mode: pixel
re_count: 1
mixup_prob: 1.0
switch_prob: 0.5
mixup_mode: batch
image_size: 384
crop_pct: 1.


# ===== Learning Rate Policy ======== #
optimizer: adamw
base_lr: 0.00002
warmup_lr: 0.00000002
min_lr: 0.0000002
lr_scheduler: cosine_lr
warmup_length: 5

# ===== Network training config ===== #
amp_level: O1
beta: [ 0.9, 0.999 ]
clip_global_norm_value: 5.
is_dynamic_loss_scale: True
epochs: 30
cooldown_epochs: 1
label_smoothing: 0.1
weight_decay: 0.00000001
momentum: 0.9
batch_size: 16
drop_path_rate: 0.3
eval_every_epoch: True
pretrained: s3:///open-data/pretrained/CoAtNet20-292_2502_384.ckpt

# ===== EMA ===== #
with_ema: False
ema_decay: 0.9999

# ===== Hardware setup ===== #
num_parallel_workers: 16
device_target: Ascend